[general]
seed = 357
workers = 30
exp_id = "test"
runs_pth = "/dmj/fizmed/mpoziomska/ELMIKO/DOKTORAT/EEGUniRep/runs"

[preprocess]
new_Fs = 128
f_stop = 64
f_pass = 40
tmin_s = 120
tmax_s = 1800
n_chans = 19

[transformations]
filters_pth = "/dmj/fizmed/mpoziomska/ELMIKO/DOKTORAT/EEGUniRep/eegunirep/eegunirep/transforms/utils/filters.json"
len_crop_s = 6
num_crops = 30
min_mask_len_perc = 0.1
max_mask_len_perc = 0.9
min_rect_len_perc = 0.1
max_rect_len_perc = 0.9
normalize = false
min_rect_amp = 100
max_rect_amp = 800
noise_mean = 0
noise_std = 10
noise_p = 0.2
cut_marigin_s = 1

[training]
epochs = 1
n_splits = 2
train_batch_size = 8
eval_batch_size = 8
base_lr = 0.2

[model]
sim_coeff = 25.0
std_coeff = 25.0
cov_coeff = 1
mlp_len_list = [ 8192, 8192, 8192,]
attention_mode = "cbam"

[neptune]
project = "EEGUniRep/Test"
api_token = "eyJhcGlfYWRkcmVzcyI6Imh0dHBzOi8vYXBwLm5lcHR1bmUuYWkiLCJhcGlfdXJsIjoiaHR0cHM6Ly9hcHAubmVwdHVuZS5haSIsImFwaV9rZXkiOiIzYjc4MGY4ZC0yOGE5LTQ4YTYtYmI1MC1kNDdjMDMzM2Q5NDUifQ=="

[model.feature_extractor]
n_temporal_filters = 40
temp_filter_length_inp = 16
spatial_expansion = 1

[model.channel_attention]
temp_filter_length = 15
